CREATE TABLE IF NOT EXISTS AccessTokens
(
    Id              INTEGER PRIMARY KEY AUTOINCREMENT,
    AccessToken     TEXT,
    UserId          INTEGER,
    TransactionHash TEXT NOT NULL, -- A hash generated by the server at the moment of creating the query
    FOREIGN KEY (UserId) REFERENCES Users (Id)
);
