CREATE TABLE IF NOT EXISTS TransactionsConfirmation
(
    Id              INTEGER PRIMARY KEY AUTOINCREMENT,
    TransactionId   INTEGER NOT NULL,  -- The id of the transaction confirmed
    ConfirmedBy     INTEGER NOT NULL,  -- The id of the user that confirmed the transaction
    Notes           TEXT DEFAULT NULL, -- Some notes left by the user that confirmed the transaction
    TransactionHash TEXT    NOT NULL,  -- A hash generated by the server at the moment of making the request
    FOREIGN KEY (TransactionId) REFERENCES Transactions (Id),
    FOREIGN KEY (ConfirmedBy) REFERENCES Users (Id)
);
