CREATE TABLE IF NOT EXISTS Transactions
(
    Id                 INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId             INTEGER NOT NULL,               -- The id of the user that made the transaction
    Amount             REAL    NOT NULL,               -- The amount of the transaction
    Currency           TEXT    NOT NULL DEFAULT 'EUR', -- The currency used for making the transaction
    CurrencyEquivalent REAL    NOT NULL DEFAULT 1,     -- The equivalent between the given currency and EUROS at the time of the transaction
    ExternalReference  TEXT             DEFAULT NULL,  -- If any, an external reference of the transaction. May be the transference number, for example
    Notes              TEXT             DEFAULT NULL,  -- Some notes left by the user that made the transaction
    TransactionHash    TEXT    NOT NULL,               -- A hash generated by the server at the moment of making the request
    FOREIGN KEY (UserId) REFERENCES Users (Id)
);
