---
--- Contains all the relations between users and scopes. This is, which users have which scopes.
--- Note that each row has a hash. This is used for verification purposes and checked against the server's private key.
---

CREATE TABLE IF NOT EXISTS UserScopes
(
    Id              INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId          INTEGER NOT NULL, -- The id of the user
    ScopeId         INTEGER NOT NULL, -- The scope given to the user
    TransactionHash TEXT    NOT NULL, -- A hash generated by the server at the moment of making the request
    FOREIGN KEY (UserId) REFERENCES Users (Id),
    FOREIGN KEY (ScopeId) REFERENCES Scopes (Id)
);
