-----------------------------------------------------------------------------------------------------------------
--- Stores all the movements between different categories that a user has made throughout their history.      ---
-----------------------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS UserHistory
(
    Id              INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId          INTEGER NOT NULL,     -- The id of the user that made the movement
    FromCategory    INTEGER DEFAULT NULL, -- The category which the user moved from. May be null if it's the user's first movement
    ToCategory      INTEGER NOT NULL,     -- The category that the user moved to.
    Timestamp       INTEGER NOT NULL,     -- The moment at which the user made the movement
    TransactionHash TEXT    NOT NULL,     -- A hash generated by the server at the moment of making the request
    FOREIGN KEY (UserId) REFERENCES Users (Id)
);
